language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
script:
- mvn clean install
after_script:
- build=$(grep "Open Liberty" target/liberty/wlp/usr/servers/defaultServer/logs/console.log | cut -d' ' -f5 | cut -d')' -f1 ); release=$( echo "$build" | cut -d'/' -f1); number=$(echo "$build" | cut -d'/' -f2); ol_jv=$(grep -i "on java" target/liberty/wlp/usr/servers/defaultServer/logs/console.log); jv=$(printf '%s\n' "${ol_jv//$' on '/$'\n'}" | sed '2q;d'); echo -e "\n"; echo -e  "\033[1;34mOpenLiberty release:\033[0m \033[1;36m$release\033[0m"; echo -e "\033[1;34mOpen Liberty build number:\033[0m \033[1;36m$number\033[0m"; echo -e "\033[1;34mJava version:\033[0m \033[1;36m$jv\033[0m";
- cd target/liberty/wlp/usr/servers/defaultServer/logs/; repo_name=$(echo "$TRAVIS_REPO_SLUG"
  | sed -e "s/\//-/g"); if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then result="passed";
  else result="failed"; fi; serverlogsarchive="$repo_name-$TRAVIS_BUILD_NUMBER-$result.zip";zip
  -r "$serverlogsarchive" .; curl -H "$JFROG_TOKEN" -T "$serverlogsarchive" "https://na.artifactory.swg-devops.com/artifactory/hyc-openliberty-guides-files-generic-local/";
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: A2sXMURizRem0TpsTyLEGzVRrv1KY/y5/4LQRA7yPT3b1JJDa8LsVHw5NID56NClKmx7B2+6qg23mqCpFlC+t0UmkIEorIfG2ba5k03wfxfZBKI54LDDTI5D+sadSD503UZM1gwY+7TQkudZJiDg5ATfJPuG4tyfu43sPDw+822r+Wz6tWgfjzMllZKd7bYKaBefTIeQ4yp00ub6e4ov2NS8xDQAnmOONctnDe3xDsZqXcbRgfU53bf9yYefoWYxUcCiQh/Lu8J2Fl6klC+K3ltrPdfmA6zd0CnEIIzwxeA7TmvLHC+Rho4zSCemHi7+kBJ6pq441h8q1ZkoVXdVMPoC4UsKEF6yODDQPF31nQI+RcdsE7STOccdQb0uoeuur29yjIHH9EEyIciDOJBagshxLSJhDqs7WdvdS7/vk0GZyNzT/KMNJyLODny42eGsllE1imAx8MvGCEi9m7Heg81Scm145FgDXjVw5VL2jqWpAoLW3p6Msd+/J2oYxdmnFTUj3n2SIzJqZE8cl3s9qs7h2cPllobrBU/fK8sO+5+/W9NeSCgKWAlGIYx4kxGfCyQO8rp25uO79NZfUeUp6GlyqHQUzSrS6Rz2h2vKU01xUpNm6mSXJkAfpG3jXIeytGut/ap8A+NK93ccuugx+98RWV+B80hxchvZ0Q7efOU=
    on_success: never
    on_failure: always
branches:
  only:
  - master
